---
- name: Deploy application
  hosts: all
  become: yes

  tasks:

    - name: Login to DockerHub
      community.docker.docker_login:
        username: "{{ docker_username }}"
        password: "{{ docker_password }}"

    - name: Pull latest Docker image
      community.docker.docker_image:
        name: "{{ docker_image }}"
        source: pull

    - name: Run container
      community.docker.docker_container:
        name: my-app
        image: "{{ docker_image }}"
        state: started
        restart_policy: always
        ports:
          - "8080:8080"

    - name: Test application
      ansible.builtin.uri:
        url: http://localhost:8080/octocat
        method: GET
        status_code: 200
        timeout: 10

    - name: Application test successful
      ansible.builtin.debug:
        msg: "GitHub Gists API is working successfully"